"""posts table

Revision ID: 648cf67e0beb
Revises: 6fce328ef206
Create Date: 2023-06-25 09:43:49.327925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '648cf67e0beb'
down_revision = '6fce328ef206'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.Column('timpstamp', sa.DateTime(), nullable=True),
    sa.Column('user_name', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_name'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_post_timpstamp'), ['timpstamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_timpstamp'))

    op.drop_table('post')
    # ### end Alembic commands ###
